-- Limpeza inicial (apenas se for seguro recriar as tabelas - CUIDADO!)
-- DROP TABLE IF EXISTS sale_items, sales, brands, products CASCADE;

-- 0.1 Tabela de Lojas (Stores)
CREATE TABLE IF NOT EXISTS stores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  nuit TEXT,
  address TEXT,
  phone TEXT,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 0.2 Tabela de Usuários/Perfis (Profiles)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  role TEXT DEFAULT 'owner',
  full_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1. Tabela de Produtos
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela de Marcas
CREATE TABLE IF NOT EXISTS brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela de Vendas
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total DECIMAL(10,2) NOT NULL,
  payment_method TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabela de Itens da Venda
CREATE TABLE IF NOT EXISTS sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES sales(id) ON DELETE CASCADE,
  brand_id BIGINT REFERENCES brands(id),
  quantity DECIMAL(10,2) NOT NULL,
  price_at_time DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL
);

-- 5. Tabela de Planos de Assinatura
CREATE TABLE IF NOT EXISTS subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  billing_cycle TEXT NOT NULL DEFAULT 'monthly',
  max_products INT DEFAULT 50,
  max_brands INT DEFAULT 100,
  max_users INT DEFAULT 1,
  has_reports BOOLEAN DEFAULT false,
  has_pos BOOLEAN DEFAULT true,
  has_priority_support BOOLEAN DEFAULT false,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Tabela de Assinaturas (vínculo loja-plano)
CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_name TEXT NOT NULL,
  plan_id BIGINT REFERENCES subscription_plans(id),
  status TEXT NOT NULL DEFAULT 'active',
  payment_method TEXT DEFAULT 'mpesa',
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  next_billing_date DATE NOT NULL,
  last_payment_date DATE,
  amount_paid DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- DESATIVAR Políticas de Segurança RLS (Para permitir testes rápidos no protótipo sem bloqueios de autenticação) --
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE brands DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions DISABLE ROW LEVEL SECURITY;

-- INSERIR DADOS MOCK INICIAIS --
INSERT INTO products (id, name, icon)
VALUES 
(1, 'Arroz', 'Box'), (2, 'Feijão', 'Package'), (3, 'Açúcar', 'Coffee'),
(4, 'Óleo', 'Droplet'), (5, 'Sabão', 'Box'), (6, 'Farinha', 'Package')
ON CONFLICT (id) DO NOTHING;

INSERT INTO brands (id, product_id, name, price, stock) 
VALUES 
(1, 1, 'Tio João', 120, 500), (2, 1, 'Bom Preço', 90, 500),
(3, 2, 'Feijão Carioca', 80, 200), (4, 2, 'Feijão Preto', 95, 200),
(5, 3, 'Açúcar Refinado', 65, 300), (6, 4, 'Óleo de Soja', 110, 100),
(7, 5, 'Sabão Azul', 25, 400), (8, 6, 'Farinha de Trigo', 50, 250)
ON CONFLICT (id) DO NOTHING;

-- PLANOS DE ASSINATURA --
INSERT INTO subscription_plans (id, name, price, billing_cycle, max_products, max_brands, max_users, has_reports, has_pos, has_priority_support, description)
VALUES 
(1, 'Básico', 300, 'monthly', 20, 50, 1, false, true, false, 'Ideal para lojas que estão a começar. Inclui POS e controle básico de stock.'),
(2, 'Profissional', 500, 'monthly', 100, 500, 3, true, true, false, 'Para lojas em crescimento. Relatórios avançados e múltiplos utilizadores.'),
(3, 'Empresarial', 800, 'monthly', -1, -1, 10, true, true, true, 'Sem limites. Suporte prioritário e funcionalidades exclusivas para redes de lojas.')
ON CONFLICT (id) DO NOTHING;

-- ASSINATURA ATIVA PARA A LOJA DEMO --
INSERT INTO subscriptions (id, store_name, plan_id, status, payment_method, start_date, next_billing_date, last_payment_date, amount_paid)
VALUES
(1, 'Loja Matola', 1, 'active', 'mpesa', '2026-03-10', '2026-04-10', '2026-03-10', 300)
ON CONFLICT (id) DO NOTHING;

-- 6. Trigger Automação de Registo: Criar perfil automaticamente no sign-up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  -- Insere o perfil automaticamente usando os campos de metadados raw_user_meta_data
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'name', 'owner');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Associar a função ao evento da base auth.users do Supabase
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
