-- ============================================================
-- COCKROACHDB SCHEMA MIGRATION
-- ============================================================

-- 0.1 Tabela de Lojas (Stores)
CREATE TABLE IF NOT EXISTS stores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  nuit TEXT,
  address TEXT,
  phone TEXT,
  email TEXT,
  owner_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  stock_low_threshold INT DEFAULT 20,
  stock_stable_threshold INT DEFAULT 50,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 0.2 Tabela de Usuários/Perfis (Profiles)
-- Removido FK para auth.users do Supabase, agora independente
CREATE TABLE IF NOT EXISTS profiles (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'owner',
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1. Tabela de Produtos
CREATE TABLE IF NOT EXISTS products (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  icon TEXT, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela de Marcas
CREATE TABLE IF NOT EXISTS brands (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INT REFERENCES products(id) ON DELETE CASCADE,
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela de Vendas
CREATE TABLE IF NOT EXISTS sales (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  profile_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  total DECIMAL(10,2) NOT NULL,
  payment_method TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabela de Itens da Venda
CREATE TABLE IF NOT EXISTS sale_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id INT REFERENCES sales(id) ON DELETE CASCADE,
  brand_id INT REFERENCES brands(id),
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  quantity DECIMAL(10,2) NOT NULL,
  price_at_time DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL
);

-- 5. Tabela de Planos de Assinatura
CREATE TABLE IF NOT EXISTS subscription_plans (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  billing_cycle TEXT NOT NULL DEFAULT 'monthly',
  max_products INT DEFAULT 50,
  max_brands INT DEFAULT 100,
  max_users INT DEFAULT 1,
  has_reports BOOLEAN DEFAULT false,
  has_pos BOOLEAN DEFAULT true,
  has_priority_support BOOLEAN DEFAULT false,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Tabela de Assinaturas (vínculo loja-plano)
CREATE TABLE IF NOT EXISTS subscriptions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  store_name TEXT NOT NULL,
  plan_id INT REFERENCES subscription_plans(id),
  status TEXT NOT NULL DEFAULT 'active',
  payment_method TEXT DEFAULT 'mpesa',
  payment_reference TEXT UNIQUE,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  next_billing_date DATE NOT NULL,
  last_payment_date DATE,
  amount_paid DECIMAL(10,2),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- PLANOS DE ASSINATURA DEFAULT --
INSERT INTO subscription_plans (id, name, price, billing_cycle, max_products, max_brands, max_users, has_reports, has_pos, has_priority_support, description)
VALUES 
(1, 'Básico', 300, 'monthly', 20, 50, 1, false, true, false, 'Ideal para lojas que estão a começar. Inclui POS e controle básico de stock.'),
(2, 'Profissional', 500, 'monthly', 100, 500, 3, true, true, false, 'Para lojas em crescimento. Relatórios avançados e múltiplos utilizadores.'),
(3, 'Empresarial', 800, 'monthly', -1, -1, 10, true, true, true, 'Sem limites. Suporte prioritário e funcionalidades exclusivas para redes de lojas.')
ON CONFLICT (id) DO NOTHING;
